[package]
name = "fan_controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99"
onlyerror = { version = "0.1", default-features = false }
uom = { version = "0.35", default-features = false, features = [
    "autoconvert",
    "f32",
    "f64",
    "si",
] }
